name: MailIt
version: @version@
main: com.drazisil.mailit.Mailit
api-version: "1.15"
authors: [Drazisil]
description: A mail system

commands:
  mail:
    description: "Check your mail."
    usage: "/<command>"
    permission: mailit.mailbox
  mail.list:
    description: "List your received packaged."
    usage: "/<command>"
    permission: mailit.mailbox
  open:
    description: "Open a package."
    usage: "/<command> <package number>"
    permission: mailit.mailbox
  send:
    description: "Send a new package."
    usage: "/<command> send <player's name>"
    permission: mailit.send
permissions:
  mailit.mailbox:
    description: Allow players to check mail
    default: true
  mailit.send:
    description: Allow players to send mail
    default: true

